### ISSUE TITLE
doesn't parse the hourly weather forecast into the .csv file.

### ISSUE THREAD

**Issue by Ehabur** [timmyoder/ISDownload#1]
Hello. Thank you for writing this code its very helpful. only problem is it shows a 3 hours forecast not hourly forecast any particular reason?

**Comment by timmyoder** [comment]
The tool is meant to download and parse the historical observations (i.e., only occurring in the past) in the NOAA ISD dataset (see: https://www.ncei.noaa.gov/products/land-based-station/integrated-surface-database). 

While other NOAA products follow similar convention, this tool is only set up for parsing those ISD files and not a forecast file.
